### ISSUE TITLE
Accepting an `AbstractRNG` argument in `rand`

### ISSUE THREAD

**Issue by rofinn** [JuliaStats/Distributions.jl#606]
I realize this issue has already been raised in #197, but it seems pretty old now. To review, Distributions.jl doesn't currently support passing an `AbstractRNG` as the first argument to the `rand` methods. In some cases, this is easy enough to change, but in several cases this will require replacing the appropriate `StatsFuns.RFunctions` calls (e.g., `binomrand` in `src/samplers/binomial.jl`). Since replacing the `R` functions is a fairly big job I'm proposing we iteratively add `rand` methods which accept an `AbstractRNG` as started in #597 and #603.

Tasks:
- [x] Add support to multivariate distributions which don't require a `RFunctions` call #597.
- [x] Add support to univariate distributions which don't require a `RFunctions` call #603.
- [x] Update `univariates/discreteuniform` once the new version of StatsBase is released (providing support for [`randi(rng, ...)`](https://github.com/JuliaStats/StatsBase.jl/commit/ba476dc594542d8d642fde0c79dab6a5d83a55ba)).
- [ ] Once all `rand` methods which don't depend on a `RFunctions` call have been updated we could probably support it generally and just have the few remaining exceptions throw an error in the `rand(rng, s)` condition.
- [ ] Look into replacing the RFunctions requirement following the discussion introduced in #294.

**Comment by rofinn** [comment]
I've been playing around the `GammaXSampler`s in order to support passing the `rng` in, but I'm not sure about the performance implications. Specifically I've enabled this code:
```julia
function sampler(d::Gamma)
    if shape(d) < 1.0
        # TODO: d.shape = 0.5 : use scaled chisq
        GammaGSSampler(d)
    elseif shape(d) == 1.0
        Exponential(scale(d))
    else
        GammaGDSampler(d)
    end
end
```
NOTE: `GammaSSampler` seems to be faster than `GammaIPSampler`.

In terms of just sampling performance the julia code appears to be almost as fast or faster than the R code.
```julia
julia> for d in [Gamma(0.1, 1.0), Gamma(0.6, 1.0), Gamma(1.0, 1.0), Gamma(2.0, 1.0), Gamma(3.0, 1.0), Gamma(1.0, 2.0), Gamma(3.0, 2.0), Gamma(100.0, 2.0)]
           s = sampler(d)
           println(string("New: ", d, " median=", median(@benchmark rand($s)), " ($(typeof(s)))"))
           println(string("Old: ", d, " median=", median(@benchmark StatsFuns.RFunctions.gammarand(shape($d), scale($d)))))
       end
New: Distributions.Gamma{Float64}(α=0.1, θ=1.0) median=TrialEstimate(52.791 ns) (Distributions.GammaGSSampler)
Old: Distributions.Gamma{Float64}(α=0.1, θ=1.0) median=TrialEstimate(42.139 ns)
New: Distributions.Gamma{Float64}(α=0.6, θ=1.0) median=TrialEstimate(74.582 ns) (Distributions.GammaGSSampler)
Old: Distributions.Gamma{Float64}(α=0.6, θ=1.0) median=TrialEstimate(58.691 ns)
New: Distributions.Gamma{Float64}(α=1.0, θ=1.0) median=TrialEstimate(10.182 ns) (Distributions.Exponential{Float64})
Old: Distributions.Gamma{Float64}(α=1.0, θ=1.0) median=TrialEstimate(45.794 ns)
New: Distributions.Gamma{Float64}(α=2.0, θ=1.0) median=TrialEstimate(44.479 ns) (Distributions.GammaGDSampler)
Old: Distributions.Gamma{Float64}(α=2.0, θ=1.0) median=TrialEstimate(41.028 ns)
New: Distributions.Gamma{Float64}(α=3.0, θ=1.0) median=TrialEstimate(45.389 ns) (Distributions.GammaGDSampler)
Old: Distributions.Gamma{Float64}(α=3.0, θ=1.0) median=TrialEstimate(40.559 ns)
New: Distributions.Gamma{Float64}(α=1.0, θ=2.0) median=TrialEstimate(9.910 ns) (Distributions.Exponential{Float64})
Old: Distributions.Gamma{Float64}(α=1.0, θ=2.0) median=TrialEstimate(45.916 ns)
New: Distributions.Gamma{Float64}(α=3.0, θ=2.0) median=TrialEstimate(45.238 ns) (Distributions.GammaGDSampler)
Old: Distributions.Gamma{Float64}(α=3.0, θ=2.0) median=TrialEstimate(40.561 ns)
New: Distributions.Gamma{Float64}(α=100.0, θ=2.0) median=TrialEstimate(21.293 ns) (Distributions.GammaGDSampler)
Old: Distributions.Gamma{Float64}(α=100.0, θ=2.0) median=TrialEstimate(23.381 ns)
```
While sampling directly from a distribution (and recreating the sampler) is usually 2-3 times slower.
```julia
julia> for d in [Gamma(0.1, 1.0), Gamma(0.6, 1.0), Gamma(1.0, 1.0), Gamma(2.0, 1.0), Gamma(3.0, 1.0), Gamma(1.0, 2.0), Gamma(3.0, 2.0), Gamma(100.0, 2.0)]
           s = sampler(d)
           println(string("New: ", d, " median=", median(@benchmark rand(sampler($d))), " ($(typeof(s)))"))
           println(string("Old: ", d, " median=", median(@benchmark StatsFuns.RFunctions.gammarand(shape($d), scale($d)))))
       end
New: Distributions.Gamma{Float64}(α=0.1, θ=1.0) median=TrialEstimate(98.111 ns) (Distributions.GammaGSSampler)
Old: Distributions.Gamma{Float64}(α=0.1, θ=1.0) median=TrialEstimate(42.079 ns)
New: Distributions.Gamma{Float64}(α=0.6, θ=1.0) median=TrialEstimate(116.508 ns) (Distributions.GammaGSSampler)
Old: Distributions.Gamma{Float64}(α=0.6, θ=1.0) median=TrialEstimate(57.890 ns)
New: Distributions.Gamma{Float64}(α=1.0, θ=1.0) median=TrialEstimate(38.510 ns) (Distributions.Exponential{Float64})
Old: Distributions.Gamma{Float64}(α=1.0, θ=1.0) median=TrialEstimate(45.531 ns)
New: Distributions.Gamma{Float64}(α=2.0, θ=1.0) median=TrialEstimate(105.904 ns) (Distributions.GammaGDSampler)
Old: Distributions.Gamma{Float64}(α=2.0, θ=1.0) median=TrialEstimate(40.981 ns)
New: Distributions.Gamma{Float64}(α=3.0, θ=1.0) median=TrialEstimate(107.973 ns) (Distributions.GammaGDSampler)
Old: Distributions.Gamma{Float64}(α=3.0, θ=1.0) median=TrialEstimate(40.706 ns)
New: Distributions.Gamma{Float64}(α=1.0, θ=2.0) median=TrialEstimate(37.879 ns) (Distributions.Exponential{Float64})
Old: Distributions.Gamma{Float64}(α=1.0, θ=2.0) median=TrialEstimate(46.037 ns)
New: Distributions.Gamma{Float64}(α=3.0, θ=2.0) median=TrialEstimate(108.131 ns) (Distributions.GammaGDSampler)
Old: Distributions.Gamma{Float64}(α=3.0, θ=2.0) median=TrialEstimate(40.071 ns)
New: Distributions.Gamma{Float64}(α=100.0, θ=2.0) median=TrialEstimate(81.817 ns) (Distributions.GammaGDSampler)
Old: Distributions.Gamma{Float64}(α=100.0, θ=2.0) median=TrialEstimate(23.228 ns)
```
Does that seem like a reasonable trade-off given the extra flexibility and increased performance in specific conditions?

**Comment by evanfields** [comment]
I'm inclined to say yes; reproducibility is super important for a lot of scientific work. In my own research code, I'd gladly take a 2x speed penalty on creating samplers if it allowed specifying the RNG and moved more of the code to pure Julia.

**Comment by nalimilan** [comment]
I'm not sure I understand the trade-off. Isn't it possible to keep using the fast path by default, and only use the slow path when a custom RNG is explicitly passed?

**Comment by rofinn** [comment]
The trade-off is just that the julia implementation is slower when `rand(rng, d)` is called many times as the sampler isn't cached (like I think it is in the R code?). This has been discussed in more detail [here](https://groups.google.com/forum/#!topic/julia-dev/fXJznjwQMF0/discussion).

The issue with only using the slow path custom RNGs is that it increases coupling between the `rand` and `sampler` methods for distributions. I'd like to see all distributions implement `sampler(::Distribution) = Sampler(...)` (possibly different samplers with the same API as an optimization like for Gamma) and a default `rand(rng::AbstractRNG, d::Distribution) = rand(rng, sampler(d))`. I suppose a middle ground could be to special case distributions that currently use Rmath so that:

```julia
sampler(d::Gamma) = ... # function above
rand(d::Gamma) = rand(GammaRmathSampler(d))
rand(rng::AbstractRNG, d::Gamma) = rand(rng, sampler(d))
```

I realize that isn't a lot of code, but that seems a little repetitive in comparison to only having a sampler method for each distribution. I'll admit that I'm biased towards decoupling distributions and samplers as much as possible as is probably apparent in #611.

**Comment by nalimilan** [comment]
I'm really not familiar with that code, but some repetition doesn't sound too bad to me, especially if that's just for distributions which still rely on Rmath.

**Comment by matbesancon** [comment]
Clsed by #830
